# Generated by Django 4.1.3 on 2022-11-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_register',
            name='slot',
            field=models.IntegerField(null=True),
        ),
    ]
