# Generated by Django 4.1.3 on 2022-11-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_company_register_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_register',
            name='slot',
            field=models.IntegerField(null=True),
        ),
    ]
