# Generated by Django 4.1.3 on 2022-11-21 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_alter_company_register_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_register',
            name='declined',
            field=models.BooleanField(default=False),
        ),
    ]
