# Generated by Django 4.1.3 on 2022-11-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='book',
            field=models.BooleanField(default=False),
        ),
    ]
