# Generated by Django 4.1.3 on 2022-11-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_alter_slot_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_register',
            name='slot',
            field=models.IntegerField(default=0),
        ),
    ]
