# Generated by Django 4.1.3 on 2022-11-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_alter_company_register_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_register',
            name='user',
            field=models.IntegerField(null=True),
        ),
    ]
